In [4]:
import pandas as pd

In [6]:
df = pd.read_excel("07.08_WATERTANKMASTER.xlsx", sheet_name = '07.08_Raw_Full')

In [10]:
df_audits = pd.read_excel("07.08_WATERTANKMASTER.xlsx", sheet_name = '07.08_Audits_Raw_Full')

In [42]:
## using excel sort: inspections date from 3/21/00 to 7/2/25
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56299 entries, 0 to 56298
Data columns (total 49 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   BIN                           56207 non-null  float64
 1   BOROUGH                       56299 non-null  object
 2   ZIP                           56220 non-null  float64
 3   HOUSE_NUM                     56299 non-null  object
 4   STREET_NAME                   56299 non-null  object
 5   BLOCK                         56299 non-null  int64
 6   LOT                           56299 non-null  int64
 7   CONFIRMATION_NUM              56299 non-null  object
 8   REPORTING_YEAR                56299 non-null  int64
 9   TANK_NUM                      56299 non-null  int64
 10  INSPECTION_BY_FIRM            56277 non-null  object
 11  INSPECTION_PERFORMED          56299 non-null  object
 12  INSPECTION_DATE               56277 non-null  datetime64[ns]
 13  GI_REQ_INTERNAL_STRUCTURE     56299 non-null  object
 14  GI_RESULT_INTERNAL_STRUCTURE  56201 non-null  object
 15  GI_REQ_EXTERNAL_STRUCTURE     56299 non-null  object
 16  GI_RESULT_EXTERNAL_STRUCTURE  56241 non-null  object
 17  GI_REQ_OVERFLOW_PIPES         56299 non-null  object
 18  GI_RESULT_OVERFLOW_PIPES      56240 non-null  object
 19  GI_REQ_ACCESS_LADDERS         56299 non-null  object
 20  GI_RESULT_ACCESS_LADDERS      56189 non-null  object
 21  GI_REQ_AIR_VENTS              56299 non-null  object
 22  GI_RESULT_AIR_VENTS           56245 non-null  object
 23  GI_REQ_ROOF_ACCESS            56299 non-null  object
 24  GI_RESULT_ROOF_ACCESS         56169 non-null  object
 25  SI_REQ_SEDIMENT               56299 non-null  object
 26  SI_RESULT_SEDIMENT            56196 non-null  object
 27  SI_REQ_BIOLOGICAL_GROWTH      56299 non-null  object
 28  SI_RESULT_BIOLOGICAL_GROWTH   56195 non-null  object
 29  SI_REQ_DEBRIS_INSECTS         56299 non-null  object
 30  SI_RESULT_DEBRIS_INSECTS      56194 non-null  object
 31  SI_REQ_RODENT_BIRD            56299 non-null  object
 32  SI_RESULT_RODENT_BIRD         56237 non-null  object
 33  SAMPLE_COLLECTED              56293 non-null  object
 34  LAB_NAME                      56182 non-null  object
 35  NYS_CERTIFIED                 56185 non-null  object
 36  ANALYTES                      56189 non-null  object
 37  COLIFORM                      56163 non-null  object
 38  ECOLI                         56163 non-null  object
 39  MEET_STANDARDS                11127 non-null  object
 40  DELETED                       56299 non-null  object
 41  LATITUDE                      56193 non-null  float64
 42  LONGITUDE                     56193 non-null  float64
 43  COMMUNITY_BOARD               56193 non-null  float64
 44  COUNCIL_DISTRICT              56193 non-null  float64
 45  CENSUS_TRACT                  56193 non-null  float64
 46  BBL                           56148 non-null  float64
 47  NTA                           56193 non-null  object
 48  BATCH_DATE                    56299 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(8), int64(4), object(35)
memory usage: 21.0+ MB

In [16]:
## 90 tanks with biological growth
df.query("SI_RESULT_BIOLOGICAL_GROWTH == 'A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
2150,1041170.0,MANHATTAN,10065.0,53,East 66th Street,1381,25,WTI0446001660,2021,1,...,NaN,No,40.767746,-73.967668,8.0,4.0,122.0,1.013810e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28
3898,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI0492131353,2021,1,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:30
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37
5067,1044738.0,MANHATTAN,10065.0,301,East 66th Street,1441,7501,WTI3342499907,2021,1,...,NaN,No,40.764846,-73.960789,8.0,5.0,118.0,1.014418e+09,Lenox Hill-Roosevelt Island,2025-07-04 12:15:30
6009,1044740.0,MANHATTAN,10065.0,333,East 66th Street,1441,17,WTI6761066587,2015,1,...,NaN,No,40.764618,-73.960247,8.0,5.0,118.0,1.014410e+09,Lenox Hill-Roosevelt Island,2025-07-04 12:15:11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52313,3327013.0,BROOKLYN,11212.0,157,Belmont Avenue,3727,1,WTI7398773309,2019,2,...,NaN,No,40.669328,-73.904350,16.0,41.0,908.0,3.037270e+09,Brownsville,2025-07-04 12:15:38
52821,3322005.0,BROOKLYN,11224.0,2930,West 28th Street,7052,14,WTI3682563848,2019,1,...,NaN,No,40.574842,-73.994186,13.0,47.0,342.0,3.070520e+09,Seagate-Coney Island,2025-07-04 12:15:38
53892,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI1789877827,2022,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28
55503,1076225.0,MANHATTAN,10023.0,25,Central Park West,1115,7501,WTI7189120614,2017,1,...,NaN,No,40.770148,-73.980400,7.0,6.0,149.0,1.011158e+09,Lincoln Square,2025-07-04 12:15:16
55995,1084520.0,MANHATTAN,10039.0,2971,Frederick Douglas Boulevard,2106,3,WTI2294705578,2019,1,...,NaN,No,40.830297,-73.936456,10.0,9.0,24302.0,1.021060e+09,Central Harlem North-Polo Grounds,2025-07-04 12:15:38

In [20]:
## 11 inspections labeled as "N" in meets standards

df.query("MEET_STANDARDS== 'N' or MEET_STANDARDS == ' '")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
18317,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI2022892081,2021,2,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:20
20838,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI1718389770,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:17
34199,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI0744599622,2021,2,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:17
35340,1001416.0,MANHATTAN,10007.0,101,BARCLAY STREET,128,2,WTI8645897156,2015,1,...,N,No,40.713767,-74.011925,1.0,1.0,21.0,1.001280e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:14
38294,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI2022892081,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:20
39605,1037986.0,MANHATTAN,10017.0,757,THIRD AVENUE,1321,1,WTI5981923701,2015,1,...,N,No,40.754035,-73.972056,6.0,4.0,90.0,1.013210e+09,Turtle Bay-East Midtown,2025-07-04 12:15:15
40486,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI1718389770,2021,2,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:17
42847,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI0744599622,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:17
43894,2096814.0,BRONX,10475.0,100,Dreiser Loop,5141,120,WTI7089234564,2022,1,...,N,No,40.878155,-73.828130,10.0,12.0,46201.0,2.051410e+09,Co-op City,2025-07-04 12:15:30
51835,2096814.0,BRONX,10475.0,100,Dreiser Loop,5141,120,WTI5663937421,2023,1,...,N,No,40.878155,-73.828130,10.0,12.0,46201.0,2.051410e+09,Co-op City,2025-07-04 12:15:26
56262,1001416.0,MANHATTAN,10007.0,101,BARCLAY STREET,128,2,WTI8645897156,2015,2,...,N,No,40.713767,-74.011925,1.0,1.0,21.0,1.001280e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:10

In [26]:
## 11,116 inspections meeting standards, 11 not meeting standards, 45172 inspections did not record
df.query("MEET_STANDARDS == 'Y'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
0,3322157.0,BROOKLYN,11223.0,2250,West 11th Street,7137,1,WTI4619292270,2020,1,...,Y,No,40.592702,-73.981572,13.0,47.0,382.0,3.071370e+09,Gravesend,2025-07-04 12:15:39
6,1016929.0,MANHATTAN,10016.0,99,MADISON AVENUE,859,24,WTI0186994800,2018,1,...,Y,No,40.744760,-73.985135,5.0,2.0,74.0,1.008590e+09,Midtown-Midtown South,2025-07-04 12:15:23
8,1048787.0,MANHATTAN,10028.0,201,EAST 86 STREET,1532,1,WTI3842932502,2017,1,...,Y,No,40.778688,-73.953642,8.0,5.0,14602.0,1.015320e+09,Yorkville,2025-07-04 12:15:16
9,1089951.0,MANHATTAN,10016.0,309,5 AVENUE,861,4,WTI0666166817,2020,1,...,Y,No,40.746841,-73.985716,5.0,4.0,74.0,1.008610e+09,Midtown-Midtown South,2025-07-04 12:15:40
10,1036205.0,MANHATTAN,10167.0,245,PARK AVENUE,1301,1,WTI5620585359,2020,1,...,Y,No,40.754826,-73.975683,5.0,4.0,92.0,1.013010e+09,Turtle Bay-East Midtown,2025-07-04 12:15:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56280,1077835.0,MANHATTAN,10012.0,3,WASHINGTON SQUARE VILLAGE,533,1,WTI4161474451,2016,4,...,Y,No,40.727881,-73.998557,2.0,1.0,5501.0,1.005330e+09,West Village,2025-07-04 12:15:12
56285,1000029.0,MANHATTAN,10004.0,2,BROADWAY,11,1,WTI1110292406,2018,1,...,Y,No,40.704119,-74.013186,1.0,1.0,9.0,1.000110e+09,Battery Park City-Lower Manhattan,2025-07-04 12:15:17
56293,1035759.0,MANHATTAN,10022.0,540,MADISON AVENUE,1290,56,WTI1291741321,2016,1,...,Y,No,40.761081,-73.973797,5.0,4.0,102.0,1.012900e+09,Midtown-Midtown South,2025-07-04 12:15:14
56294,1050351.0,MANHATTAN,10075.0,430,EAST 80 STREET,1559,31,WTI6551902953,2016,1,...,Y,No,40.772560,-73.951119,8.0,5.0,136.0,1.015590e+09,Yorkville,2025-07-04 12:15:12
56297,1001862.0,MANHATTAN,10013.0,366,BROADWAY,172,1,WTI8646843953,2018,1,...,Y,No,40.717591,-74.003402,1.0,1.0,31.0,1.001720e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:24

In [32]:
##17 water tanks had coliform present
df.query("COLIFORM=='P'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
4202,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI0233832515,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
7115,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI7297474305,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:36
8920,1059410.0,MANHATTAN,10031.0,181,Convent Avenue,1957,100,WTI8044405574,2024,2,...,NaN,No,40.819574,-73.949921,9.0,9.0,21703.0,1.019570e+09,Manhattanville,2025-07-04 12:15:36
9726,3396962.0,BROOKLYN,11201.0,138,Willoughby Street,149,7502,WTI1195906715,2024,1,...,NaN,No,40.692069,-73.983135,2.0,33.0,15.0,3.001498e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:28
12925,3057474.0,BROOKLYN,11217.0,62,HANSON PLACE,2003,19,WTI5724184982,2023,1,...,NaN,No,40.685414,-73.975096,2.0,35.0,35.0,3.020030e+09,Fort Greene,2025-07-04 12:15:42
15259,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI7213119116,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:36
20370,2097550.0,BRONX,10461.0,1400,Pelham Parkway South,4205,1,WTI1453857536,2017,4,...,NaN,No,40.857427,-73.847079,11.0,13.0,296.0,2.042050e+09,Pelham Parkway,2025-07-04 12:15:23
25261,3002105.0,BROOKLYN,11201.0,180,Montague Street,250,30,WTI5611397937,2017,1,...,NaN,No,40.694079,-73.991756,2.0,33.0,9.0,3.002500e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:18
32295,3057474.0,BROOKLYN,11217.0,62,HANSON PLACE,2003,19,WTI7325560059,2023,1,...,NaN,No,40.685414,-73.975096,2.0,35.0,35.0,3.020030e+09,Fort Greene,2025-07-04 12:15:31
34492,1029649.0,MANHATTAN,10023.0,114,West 70th Street,1141,37,WTI2669150648,2015,1,...,NaN,No,40.776318,-73.980265,7.0,6.0,153.0,1.011410e+09,Lincoln Square,2025-07-04 12:15:13
41827,3002105.0,BROOKLYN,11201.0,180,Montague Street,250,30,WTI6035952677,2017,1,...,NaN,No,40.694079,-73.991756,2.0,33.0,9.0,3.002500e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:18
45497,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI9636716838,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
47329,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI0197965656,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
47957,4436685.0,QUEENS,11101.0,45-30,36 Street,226,1,WTI3673561835,2018,2,...,NaN,No,40.743509,-73.929076,2.0,26.0,179.0,4.002260e+09,Hunters Point-Sunnyside-West Maspeth,2025-07-04 12:15:22
48875,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI7028194986,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
50616,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI2728713976,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:20
52588,2097550.0,BRONX,10461.0,1400,Pelham Parkway South,4205,1,WTI1453857536,2017,3,...,NaN,No,40.857427,-73.847079,11.0,13.0,296.0,2.042050e+09,Pelham Parkway,2025-07-04 12:15:23

In [36]:
## 18 tanks had ECOLI present
df.query("ECOLI=='P'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
4202,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI0233832515,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
4361,1001830.0,MANHATTAN,10013.0,80,Centre Street,166,27,WTI2876759159,2015,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:13
7115,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI7297474305,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:36
10349,1001833.0,MANHATTAN,10013.0,111,Centre Street,169,10,WTI5972678056,2015,1,...,NaN,No,40.716317,-74.001277,1.0,1.0,31.0,1.001690e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:13
15259,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI7213119116,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:36
20838,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI1718389770,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:17
25261,3002105.0,BROOKLYN,11201.0,180,Montague Street,250,30,WTI5611397937,2017,1,...,NaN,No,40.694079,-73.991756,2.0,33.0,9.0,3.002500e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:18
33428,1002358.0,MANHATTAN,10013.0,137,Centre Street,197,17,WTI8449898896,2015,1,...,NaN,No,40.717157,-74.000653,1.0,1.0,31.0,1.001970e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:15
33993,3056987.0,BROOKLYN,11238.0,45,Monroe Street,1985,55,WTI1249652878,2015,1,...,NaN,No,40.684695,-73.957367,3.0,35.0,229.0,3.019850e+09,Clinton Hill,2025-07-04 12:15:12
34492,1029649.0,MANHATTAN,10023.0,114,West 70th Street,1141,37,WTI2669150648,2015,1,...,NaN,No,40.776318,-73.980265,7.0,6.0,153.0,1.011410e+09,Lincoln Square,2025-07-04 12:15:13
36386,3000534.0,BROOKLYN,11201.0,120,Schermerhorn Street,169,17,WTI8756988209,2015,1,...,NaN,No,40.690074,-73.988923,2.0,33.0,43.0,3.001690e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:12
38294,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI2022892081,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:20
41827,3002105.0,BROOKLYN,11201.0,180,Montague Street,250,30,WTI6035952677,2017,1,...,NaN,No,40.694079,-73.991756,2.0,33.0,9.0,3.002500e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:18
42847,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI0744599622,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:17
45497,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI9636716838,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
47329,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI0197965656,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
48875,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI7028194986,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
50616,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI2728713976,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:20

In [40]:
## 10 tanks had both coliform and ECOLI
df.query("(COLIFORM=='P') and (ECOLI=='P')")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
4202,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI0233832515,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
7115,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI7297474305,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:36
15259,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI7213119116,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:36
25261,3002105.0,BROOKLYN,11201.0,180,Montague Street,250,30,WTI5611397937,2017,1,...,NaN,No,40.694079,-73.991756,2.0,33.0,9.0,3.002500e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:18
34492,1029649.0,MANHATTAN,10023.0,114,West 70th Street,1141,37,WTI2669150648,2015,1,...,NaN,No,40.776318,-73.980265,7.0,6.0,153.0,1.011410e+09,Lincoln Square,2025-07-04 12:15:13
41827,3002105.0,BROOKLYN,11201.0,180,Montague Street,250,30,WTI6035952677,2017,1,...,NaN,No,40.694079,-73.991756,2.0,33.0,9.0,3.002500e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:18
45497,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI9636716838,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
47329,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI0197965656,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
48875,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI7028194986,2022,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28
50616,5127737.0,STATEN ISLAND,10307.0,35,Hale Street,8034,45,WTI2728713976,2000,1,...,NaN,Yes,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:20

In [98]:
df["INSPECTION_DATE"] = pd.to_datetime(df["INSPECTION_DATE"], format="%m/%d/%Y")

In [100]:
start_date = pd.Timestamp("2020-01-01")
end_date = pd.Timestamp("2025-07-02")

In [102]:
# filter the dataframe from 2020 to July 8 2025
df20tonow = df[(df["INSPECTION_DATE"] >= start_date) & (df["INSPECTION_DATE"] <= end_date)]

In [104]:
df20tonow_dirty = df20tonow.query("(SI_RESULT_SEDIMENT=='A') or (SI_RESULT_BIOLOGICAL_GROWTH=='A') or (SI_RESULT_DEBRIS_INSECTS=='A') or (SI_RESULT_RODENT_BIRD=='A') or (SI_RESULT_BIOLOGICAL_GROWTH == 'A') or (COLIFORM == 'P') or (ECOLI == 'P')")

In [106]:
## 46 tanks between 2020-2025 had biological growth
df20tonow_dirty.query("SI_RESULT_BIOLOGICAL_GROWTH=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
2150,1041170.0,MANHATTAN,10065.0,53,East 66th Street,1381,25,WTI0446001660,2021,1,...,NaN,No,40.767746,-73.967668,8.0,4.0,122.0,1.013810e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28
3898,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI0492131353,2021,1,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:30
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37
5067,1044738.0,MANHATTAN,10065.0,301,East 66th Street,1441,7501,WTI3342499907,2021,1,...,NaN,No,40.764846,-73.960789,8.0,5.0,118.0,1.014418e+09,Lenox Hill-Roosevelt Island,2025-07-04 12:15:30
6396,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI5649907212,2021,1,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:30
7867,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,1,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
10273,1041848.0,MANHATTAN,10075.0,969,Fifth Avenue,1392,69,WTI8826904066,2020,1,...,NaN,No,40.776111,-73.963992,8.0,4.0,142.0,1.013920e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26
12088,1041170.0,MANHATTAN,10065.0,53,East 66th Street,1381,25,WTI1301924385,2021,1,...,NaN,No,40.767746,-73.967668,8.0,4.0,122.0,1.013810e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:16
17273,3001881.0,BROOKLYN,11201.0,45,monroe place,237,1,WTI5577496755,2021,1,...,NaN,No,40.695822,-73.992802,2.0,33.0,502.0,3.002370e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:28
17725,1046777.0,MANHATTAN,10028.0,1020,Fifth Avenue,1495,1,WTI2347475303,2021,1,...,NaN,No,40.779558,-73.961531,8.0,4.0,142.0,1.014950e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28
20328,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI7611505795,2022,1,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28
20394,1074157.0,MANHATTAN,10029.0,1220,Fifth Avenue,1609,1,WTI6586276748,2021,1,...,NaN,No,40.792438,-73.952448,11.0,8.0,168.0,1.016090e+09,East Harlem South,2025-07-04 12:15:30
21479,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI7611505795,2022,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28
23125,1077512.0,MANHATTAN,10002.0,160,Madison Street,255,1,WTI0692171448,2020,1,...,NaN,No,40.712488,-73.991924,3.0,1.0,6.0,1.002550e+09,Lower East Side,2025-07-04 12:15:22
24087,1041814.0,MANHATTAN,10075.0,955,Fifth Avenue,1391,72,WTI6350984339,2020,1,...,NaN,No,40.775466,-73.964830,8.0,4.0,130.0,1.013910e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26
29471,1040543.0,MANHATTAN,10022.0,4,Sutton Place,1369,24,WTI8716577061,2020,1,...,NaN,No,40.757512,-73.960576,6.0,5.0,10601.0,1.013690e+09,Turtle Bay-East Midtown,2025-07-04 12:15:26
30271,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI9685378701,2020,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:37
31184,1038770.0,MANHATTAN,10017.0,310,East 46th Street,1338,5,WTI4477195314,2020,1,...,NaN,No,40.752154,-73.969834,6.0,4.0,90.0,1.013380e+09,Turtle Bay-East Midtown,2025-07-04 12:15:26
32087,1074157.0,MANHATTAN,10029.0,1220,Fifth Avenue,1609,1,WTI3318732840,2021,1,...,NaN,No,40.792438,-73.952448,11.0,8.0,168.0,1.016090e+09,East Harlem South,2025-07-04 12:15:28
33202,3001881.0,BROOKLYN,11201.0,45,Monroe Place,237,1,WTI8950358964,2020,1,...,NaN,No,40.695822,-73.992802,2.0,33.0,502.0,3.002370e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35
35039,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI9685378701,2020,1,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:37
35204,1042806.0,MANHATTAN,10021.0,140,East 72nd Street,1406,17,WTI6092846004,2021,1,...,NaN,No,40.770533,-73.962493,8.0,4.0,128.0,1.014060e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28
35217,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI5649907212,2021,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:30
35377,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI1143990704,2022,1,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28
35407,1044738.0,MANHATTAN,10065.0,301,East 66th Street,1441,7501,WTI4749968013,2021,1,...,NaN,No,40.764846,-73.960789,8.0,5.0,118.0,1.014418e+09,Lenox Hill-Roosevelt Island,2025-07-04 12:15:28
35976,3001881.0,BROOKLYN,11201.0,45,monroe place,237,1,WTI5479372124,2024,1,...,NaN,No,40.695822,-73.992802,2.0,33.0,502.0,3.002370e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:42
36437,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI1143990704,2022,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28
37094,1042806.0,MANHATTAN,10021.0,140,East 72nd Street,1406,17,WTI3213853242,2021,1,...,NaN,No,40.770533,-73.962493,8.0,4.0,128.0,1.014060e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:41
37702,1001830.0,MANHATTAN,10013.0,80,Centre street,166,27,WTI4837019370,2021,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:30
38294,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI2022892081,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:20
40081,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI2400327671,2020,1,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
40153,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI2400327671,2020,2,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
40271,3001881.0,BROOKLYN,11201.0,45,monroe place,237,1,WTI5392621679,2021,1,...,NaN,No,40.695822,-73.992802,2.0,33.0,502.0,3.002370e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:30
41171,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,2,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
42729,1046953.0,MANHATTAN,10128.0,47,East 88th Street,1500,20,WTI3885353468,2021,1,...,NaN,No,40.781980,-73.957410,8.0,4.0,15002.0,1.015000e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28
43288,1038645.0,MANHATTAN,10016.0,305,East 40th Street,1333,1,WTI7127696291,2021,1,...,NaN,No,40.748469,-73.972954,6.0,4.0,88.0,1.013330e+09,Turtle Bay-East Midtown,2025-07-04 12:15:28
44880,1015067.0,MANHATTAN,10001.0,121,West 27th St,803,21,WTI0569540150,2022,1,...,NaN,No,40.745831,-73.991916,5.0,3.0,95.0,1.008030e+09,Midtown-Midtown South,2025-07-04 12:15:27
45471,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI0492131353,2021,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:30
48269,1038645.0,MANHATTAN,10016.0,305,East 40th Street,1333,1,WTI1179716163,2021,1,...,NaN,No,40.748469,-73.972954,6.0,4.0,88.0,1.013330e+09,Turtle Bay-East Midtown,2025-07-04 12:15:32
48329,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI6205574006,2020,1,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
48384,1046953.0,MANHATTAN,10128.0,47,East 88th Street,1500,20,WTI6639349033,2021,1,...,NaN,No,40.781980,-73.957410,8.0,4.0,15002.0,1.015000e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:32
48956,1001830.0,MANHATTAN,10013.0,80,Centre street,166,27,WTI1249835620,2021,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:28
49948,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI1789877827,2022,1,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28
50967,1040884.0,MANHATTAN,10065.0,812,Fifth Avenue,1377,3,WTI0297133513,2021,1,...,NaN,No,40.766378,-73.971459,8.0,4.0,11401.0,1.013770e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:32
51310,1040884.0,MANHATTAN,10065.0,812,Fifth Avenue,1377,3,WTI1166039726,2021,1,...,NaN,No,40.766378,-73.971459,8.0,4.0,11401.0,1.013770e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28
53892,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI1789877827,2022,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28

In [108]:
## 65 water tanks have insect debris
df20tonow_dirty.query("SI_RESULT_DEBRIS_INSECTS=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
329,1046861.0,MANHATTAN,10028.0,1056,Fifth Avenue,1498,69,WTI7980345404,2020,1,...,NaN,No,40.782107,-73.959988,8.0,4.0,15002.0,1.014980e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26
690,1079000.0,MANHATTAN,10013.0,100,Centre street,167,1,WTI2165831892,2021,1,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,2025-07-04 12:15:28
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37
6564,2097114.0,BRONX,10451.0,265,east 161 street,2444,1,WTI5110338241,2021,1,...,NaN,No,40.825928,-73.919514,4.0,16.0,18302.0,2.024440e+09,East Concourse-Concourse Village,2025-07-04 12:15:28
7226,3396962.0,BROOKLYN,11201.0,138,Willoughby Street,149,1,WTI4465022999,2021,4,...,NaN,No,40.692069,-73.983135,2.0,33.0,15.0,3.001498e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51314,3392969.0,BROOKLYN,11201.0,345,Adams Street,140,7503,WTI0991844172,2020,2,...,NaN,No,40.693400,-73.988915,2.0,33.0,11.0,3.001408e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:35
51419,1085748.0,MANHATTAN,10007.0,60,centre street,160,21,WTI1657686092,2021,2,...,NaN,No,40.714467,-74.002503,1.0,1.0,29.0,1.001600e+09,Chinatown,2025-07-04 12:15:30
52742,1079000.0,MANHATTAN,10013.0,100,Centre Street,167,1,WTI2666744471,2022,2,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,2025-07-04 12:15:28
53892,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI1789877827,2022,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28
54874,1079000.0,MANHATTAN,10013.0,100,Centre Street,167,1,WTI7177028402,2022,1,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,2025-07-04 12:15:28

In [66]:
## 20 tanks had rodent or bird debris
df20tonow_dirty.query("SI_RESULT_RODENT_BIRD=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37
7867,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,1,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
8808,1078858.0,MANHATTAN,10029.0,70,East 108th Street,1613,23,WTI3538482346,2020,1,...,NaN,No,40.794429,-73.947434,11.0,8.0,17401.0,1.016130e+09,East Harlem South,2025-07-04 12:15:22
8933,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,2,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35
10030,1041332.0,MANHATTAN,10021.0,720,Park Avenue,1385,32,WTI6304305629,2021,1,...,NaN,No,40.769950,-73.964681,8.0,4.0,130.0,1.013850e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:30
11072,1041332.0,MANHATTAN,10021.0,720,Park Avenue,1385,32,WTI7305156430,2021,1,...,NaN,No,40.769950,-73.964681,8.0,4.0,130.0,1.013850e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28
13662,1027087.0,MANHATTAN,10036.0,520,12th Ave,1090,1,WTI9977468480,2021,1,...,NaN,No,40.762316,-74.000036,4.0,3.0,129.0,1.010900e+09,Clinton,2025-07-04 12:15:26
17042,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI6999130303,2021,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:28
20016,1078858.0,MANHATTAN,10029.0,70,East 108th Street,1613,23,WTI3538482346,2020,2,...,NaN,No,40.794429,-73.947434,11.0,8.0,17401.0,1.016130e+09,East Harlem South,2025-07-04 12:15:22
20907,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI7080721393,2020,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:35
30271,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI9685378701,2020,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:37
34084,1077512.0,MANHATTAN,10002.0,160,Madison Street,255,1,WTI0692171448,2020,2,...,NaN,No,40.712488,-73.991924,3.0,1.0,6.0,1.002550e+09,Lower East Side,2025-07-04 12:15:22
38294,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI2022892081,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:20
40153,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI2400327671,2020,2,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
41171,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,2,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
41204,1084673.0,MANHATTAN,10019.0,15,West 56th Street,1272,26,WTI7792919211,2021,1,...,NaN,No,40.762640,-73.975258,5.0,4.0,11201.0,1.012720e+09,Midtown-Midtown South,2025-07-04 12:15:20
41973,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,1,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35
42184,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI4354141630,2021,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:30
42847,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI0744599622,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:17
48404,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,3,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35

In [70]:
## 65 tanks had insect debris
df20tonow_dirty.query("SI_RESULT_DEBRIS_INSECTS=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
329,1046861.0,MANHATTAN,10028.0,1056,Fifth Avenue,1498,69,WTI7980345404,2020,1,...,NaN,No,40.782107,-73.959988,8.0,4.0,15002.0,1.014980e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26
690,1079000.0,MANHATTAN,10013.0,100,Centre street,167,1,WTI2165831892,2021,1,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,2025-07-04 12:15:28
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37
6564,2097114.0,BRONX,10451.0,265,east 161 street,2444,1,WTI5110338241,2021,1,...,NaN,No,40.825928,-73.919514,4.0,16.0,18302.0,2.024440e+09,East Concourse-Concourse Village,2025-07-04 12:15:28
7226,3396962.0,BROOKLYN,11201.0,138,Willoughby Street,149,1,WTI4465022999,2021,4,...,NaN,No,40.692069,-73.983135,2.0,33.0,15.0,3.001498e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51314,3392969.0,BROOKLYN,11201.0,345,Adams Street,140,7503,WTI0991844172,2020,2,...,NaN,No,40.693400,-73.988915,2.0,33.0,11.0,3.001408e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:35
51419,1085748.0,MANHATTAN,10007.0,60,centre street,160,21,WTI1657686092,2021,2,...,NaN,No,40.714467,-74.002503,1.0,1.0,29.0,1.001600e+09,Chinatown,2025-07-04 12:15:30
52742,1079000.0,MANHATTAN,10013.0,100,Centre Street,167,1,WTI2666744471,2022,2,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,2025-07-04 12:15:28
53892,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI1789877827,2022,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:28
54874,1079000.0,MANHATTAN,10013.0,100,Centre Street,167,1,WTI7177028402,2022,1,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,2025-07-04 12:15:28

In [110]:
## 12 tanks had both rodent and insect debris
df20tonow_dirty.query("(SI_RESULT_RODENT_BIRD=='A') and (SI_RESULT_DEBRIS_INSECTS=='A')")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37
7867,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,1,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
8933,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,2,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35
17042,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI6999130303,2021,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:28
20907,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI7080721393,2020,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:35
30271,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI9685378701,2020,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:37
40153,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI2400327671,2020,2,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
41171,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,2,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29
41204,1084673.0,MANHATTAN,10019.0,15,West 56th Street,1272,26,WTI7792919211,2021,1,...,NaN,No,40.762640,-73.975258,5.0,4.0,11201.0,1.012720e+09,Midtown-Midtown South,2025-07-04 12:15:20
41973,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,1,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35
42184,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI4354141630,2021,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:30
48404,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,3,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35

In [112]:
## merge columns in df to create a full address column for dropping duplicates
df20tonow_dirty['ADDRESS'] = df20tonow_dirty['HOUSE_NUM'].astype(str)+ ' ' + df20tonow_dirty['STREET_NAME'].astype(str)

/var/folders/rc/n80vvwzn0cgc5d6p28yqkgtm0000gn/T/ipykernel_4775/560339458.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df20tonow_dirty['ADDRESS'] = df20tonow_dirty['HOUSE_NUM'].astype(str)+ ' ' + df20tonow_dirty['STREET_NAME'].astype(str)

In [114]:
df20tonow_dirty['ADDRESS_NORM'] = df20tonow_dirty['ADDRESS'].str.lower().str.strip()

/var/folders/rc/n80vvwzn0cgc5d6p28yqkgtm0000gn/T/ipykernel_4775/152555719.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df20tonow_dirty['ADDRESS_NORM'] = df20tonow_dirty['ADDRESS'].str.lower().str.strip()

In [116]:
df20tonow_dirty.sample(2)

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
42184,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI4354141630,2021,1,...,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:30,1118 Grand Concourse,1118 grand concourse
32105,3396962.0,BROOKLYN,11201.0,138,Willoughby Street,149,1,WTI0365167644,2022,2,...,40.692069,-73.983135,2.0,33.0,15.0,3.001498e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:35,138 Willoughby Street,138 willoughby street

In [118]:
## sort the df so most recent inspection comes first
df20tonow_dirty_sorted = df20tonow_dirty.sort_values('INSPECTION_DATE', ascending=False)

In [122]:
df20tonow_dirty_sorted.head(6)

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
37279,1041332.0,MANHATTAN,10021.0,720,Park Avenue,1385,32,WTI7544137616,2025,1,...,40.769950,-73.964681,8.0,4.0,130.0,1.013850e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:31,720 Park Avenue,720 park avenue
35992,1042830.0,MANHATTAN,10021.0,755,Park Avenue,1406,69,WTI5909463778,2025,1,...,40.770795,-73.963511,8.0,4.0,128.0,1.014060e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:31,755 Park Avenue,755 park avenue
14287,1041377.0,MANHATTAN,10021.0,4,East 72nd Street,1386,64,WTI2200809264,2025,1,...,40.772311,-73.966702,8.0,4.0,130.0,1.013860e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:23,4 East 72nd Street,4 east 72nd street
29301,1014515.0,MANHATTAN,10011.0,77,Seventh Avenue,790,1,WTI3290400543,2025,1,...,40.738906,-73.999415,4.0,3.0,81.0,1.007900e+09,Hudson Yards-Chelsea-Flatiron-Union Square,2025-07-04 12:15:21,77 Seventh Avenue,77 seventh avenue
41016,1014515.0,MANHATTAN,10011.0,77,Seventh Avenue,790,1,WTI2023335641,2025,1,...,40.738906,-73.999415,4.0,3.0,81.0,1.007900e+09,Hudson Yards-Chelsea-Flatiron-Union Square,2025-07-04 12:15:21,77 Seventh Avenue,77 seventh avenue
47720,1044838.0,MANHATTAN,10021.0,331,East 70th Street,1445,14,WTI3634144196,2025,1,...,40.766925,-73.957950,8.0,5.0,126.0,1.014450e+09,Lenox Hill-Roosevelt Island,2025-07-04 12:15:31,331 East 70th Street,331 east 70th street

In [126]:
df20tonow_dirty_nodupes = df20tonow_dirty.drop_duplicates(subset='ADDRESS_NORM')

In [128]:
df20tonow_dirty_nodupes.sample(3)

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
9310,1051388.0,MANHATTAN,10028.0,1,Gracie Square,1590,42,WTI2988185882,2024,1,...,40.773538,-73.945558,8.0,5.0,136.0,1.015900e+09,Yorkville,2025-07-04 12:15:30,1 Gracie Square,1 gracie square
16443,1040543.0,MANHATTAN,10022.0,4,Sutton Place,1369,24,WTI2118094127,2021,1,...,40.757512,-73.960576,6.0,5.0,10601.0,1.013690e+09,Turtle Bay-East Midtown,2025-07-04 12:15:28,4 Sutton Place,4 sutton place
16865,1085748.0,MANHATTAN,10007.0,60,centre street,160,21,WTI4217862121,2020,2,...,40.714467,-74.002503,1.0,1.0,29.0,1.001600e+09,Chinatown,2025-07-04 12:15:19,60 centre street,60 centre street

In [134]:
## 127 tanks between 2020 and july 2025 had a contamination violation
df20tonow_dirty_nodupes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 127 entries, 44 to 54398
Data columns (total 51 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   BIN                           127 non-null    float64
 1   BOROUGH                       127 non-null    object
 2   ZIP                           127 non-null    float64
 3   HOUSE_NUM                     127 non-null    object
 4   STREET_NAME                   127 non-null    object
 5   BLOCK                         127 non-null    int64
 6   LOT                           127 non-null    int64
 7   CONFIRMATION_NUM              127 non-null    object
 8   REPORTING_YEAR                127 non-null    int64
 9   TANK_NUM                      127 non-null    int64
 10  INSPECTION_BY_FIRM            127 non-null    object
 11  INSPECTION_PERFORMED          127 non-null    object
 12  INSPECTION_DATE               127 non-null    datetime64[ns]
 13  GI_REQ_INTERNAL_STRUCTURE     127 non-null    object
 14  GI_RESULT_INTERNAL_STRUCTURE  126 non-null    object
 15  GI_REQ_EXTERNAL_STRUCTURE     127 non-null    object
 16  GI_RESULT_EXTERNAL_STRUCTURE  126 non-null    object
 17  GI_REQ_OVERFLOW_PIPES         127 non-null    object
 18  GI_RESULT_OVERFLOW_PIPES      126 non-null    object
 19  GI_REQ_ACCESS_LADDERS         127 non-null    object
 20  GI_RESULT_ACCESS_LADDERS      126 non-null    object
 21  GI_REQ_AIR_VENTS              127 non-null    object
 22  GI_RESULT_AIR_VENTS           126 non-null    object
 23  GI_REQ_ROOF_ACCESS            127 non-null    object
 24  GI_RESULT_ROOF_ACCESS         126 non-null    object
 25  SI_REQ_SEDIMENT               127 non-null    object
 26  SI_RESULT_SEDIMENT            126 non-null    object
 27  SI_REQ_BIOLOGICAL_GROWTH      127 non-null    object
 28  SI_RESULT_BIOLOGICAL_GROWTH   125 non-null    object
 29  SI_REQ_DEBRIS_INSECTS         127 non-null    object
 30  SI_RESULT_DEBRIS_INSECTS      126 non-null    object
 31  SI_REQ_RODENT_BIRD            127 non-null    object
 32  SI_RESULT_RODENT_BIRD         125 non-null    object
 33  SAMPLE_COLLECTED              127 non-null    object
 34  LAB_NAME                      124 non-null    object
 35  NYS_CERTIFIED                 124 non-null    object
 36  ANALYTES                      124 non-null    object
 37  COLIFORM                      124 non-null    object
 38  ECOLI                         124 non-null    object
 39  MEET_STANDARDS                1 non-null      object
 40  DELETED                       127 non-null    object
 41  LATITUDE                      127 non-null    float64
 42  LONGITUDE                     127 non-null    float64
 43  COMMUNITY_BOARD               127 non-null    float64
 44  COUNCIL_DISTRICT              127 non-null    float64
 45  CENSUS_TRACT                  127 non-null    float64
 46  BBL                           127 non-null    float64
 47  NTA                           127 non-null    object
 48  BATCH_DATE                    127 non-null    datetime64[ns]
 49  ADDRESS                       127 non-null    object
 50  ADDRESS_NORM                  127 non-null    object
dtypes: datetime64[ns](2), float64(8), int64(4), object(37)
memory usage: 51.6+ KB

In [130]:
df20tonow_dirty_nodupes.to_csv("01.01.20-07.08.25_dirty_dropdupes.csv")

## reanalyze the new data set: ("(SI_RESULT_SEDIMENT=='A') or (SI_RESULT_BIOLOGICAL_GROWTH=='A') or (SI_RESULT_DEBRIS_INSECTS=='A') or (SI_RESULT_RODENT_BIRD=='A') or (SI_RESULT_BIOLOGICAL_GROWTH == 'A') or (COLIFORM == 'P') or (ECOLI == 'P')")

In [138]:
#8 tanks had rodent/bird debris
df20tonow_dirty_nodupes.query("SI_RESULT_RODENT_BIRD=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37,80 centre street,80 centre street
7867,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,1,...,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29,31 Chambers street,31 chambers street
8808,1078858.0,MANHATTAN,10029.0,70,East 108th Street,1613,23,WTI3538482346,2020,1,...,40.794429,-73.947434,11.0,8.0,17401.0,1.016130e+09,East Harlem South,2025-07-04 12:15:22,70 East 108th Street,70 east 108th street
8933,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,2,...,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35,210 Joralemon Street,210 joralemon street
10030,1041332.0,MANHATTAN,10021.0,720,Park Avenue,1385,32,WTI6304305629,2021,1,...,40.769950,-73.964681,8.0,4.0,130.0,1.013850e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:30,720 Park Avenue,720 park avenue
13662,1027087.0,MANHATTAN,10036.0,520,12th Ave,1090,1,WTI9977468480,2021,1,...,40.762316,-74.000036,4.0,3.0,129.0,1.010900e+09,Clinton,2025-07-04 12:15:26,520 12th Ave,520 12th ave
17042,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI6999130303,2021,1,...,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:28,1118 Grand Concourse,1118 grand concourse
41204,1084673.0,MANHATTAN,10019.0,15,West 56th Street,1272,26,WTI7792919211,2021,1,...,40.762640,-73.975258,5.0,4.0,11201.0,1.012720e+09,Midtown-Midtown South,2025-07-04 12:15:20,15 West 56th Street,15 west 56th street

In [140]:
## 16 tanks had insect debris
df20tonow_dirty_nodupes.query("SI_RESULT_DEBRIS_INSECTS=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
329,1046861.0,MANHATTAN,10028.0,1056,Fifth Avenue,1498,69,WTI7980345404,2020,1,...,40.782107,-73.959988,8.0,4.0,15002.0,1.014980e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26,1056 Fifth Avenue,1056 fifth avenue
690,1079000.0,MANHATTAN,10013.0,100,Centre street,167,1,WTI2165831892,2021,1,...,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,2025-07-04 12:15:28,100 Centre street,100 centre street
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37,80 centre street,80 centre street
6564,2097114.0,BRONX,10451.0,265,east 161 street,2444,1,WTI5110338241,2021,1,...,40.825928,-73.919514,4.0,16.0,18302.0,2.024440e+09,East Concourse-Concourse Village,2025-07-04 12:15:28,265 east 161 street,265 east 161 street
7226,3396962.0,BROOKLYN,11201.0,138,Willoughby Street,149,1,WTI4465022999,2021,4,...,40.692069,-73.983135,2.0,33.0,15.0,3.001498e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:32,138 Willoughby Street,138 willoughby street
7867,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,1,...,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29,31 Chambers street,31 chambers street
8933,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,2,...,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:35,210 Joralemon Street,210 joralemon street
10273,1041848.0,MANHATTAN,10075.0,969,Fifth Avenue,1392,69,WTI8826904066,2020,1,...,40.776111,-73.963992,8.0,4.0,142.0,1.013920e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26,969 Fifth Avenue,969 fifth avenue
14562,1036441.0,MANHATTAN,10022.0,541,Lexington Avenue,1304,20,WTI5138681753,2021,1,...,40.756162,-73.972593,6.0,4.0,100.0,1.013040e+09,Turtle Bay-East Midtown,2025-07-04 12:15:32,541 Lexington Avenue,541 lexington avenue
16865,1085748.0,MANHATTAN,10007.0,60,centre street,160,21,WTI4217862121,2020,2,...,40.714467,-74.002503,1.0,1.0,29.0,1.001600e+09,Chinatown,2025-07-04 12:15:19,60 centre street,60 centre street
17042,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI6999130303,2021,1,...,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,2025-07-04 12:15:28,1118 Grand Concourse,1118 grand concourse
21088,3335892.0,BROOKLYN,11201.0,300,Jay Street,128,1,WTI0590884260,2022,2,...,40.695547,-73.987140,2.0,33.0,13.0,3.001280e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2025-07-04 12:15:26,300 Jay Street,300 jay street
25361,1080707.0,MANHATTAN,10029.0,230,East 115th Street,1662,1,WTI6137520645,2020,1,...,40.796689,-73.939208,11.0,8.0,180.0,1.016620e+09,East Harlem North,2025-07-04 12:15:22,230 East 115th Street,230 east 115th street
32720,1040884.0,MANHATTAN,10065.0,812,Fifth Avenue,1377,3,WTI9037866115,2020,1,...,40.766378,-73.971459,8.0,4.0,11401.0,1.013770e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26,812 Fifth Avenue,812 fifth avenue
41204,1084673.0,MANHATTAN,10019.0,15,West 56th Street,1272,26,WTI7792919211,2021,1,...,40.762640,-73.975258,5.0,4.0,11201.0,1.012720e+09,Midtown-Midtown South,2025-07-04 12:15:20,15 West 56th Street,15 west 56th street
49750,1040542.0,MANHATTAN,10022.0,455,East 57th Street,1369,19,WTI1545885615,2020,1,...,40.757809,-73.961713,6.0,5.0,10601.0,1.013690e+09,Turtle Bay-East Midtown,2025-07-04 12:15:37,455 East 57th Street,455 east 57th street

In [142]:
##12 tanks had bio growth
df20tonow_dirty_nodupes.query("SI_RESULT_BIOLOGICAL_GROWTH == 'A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
2150,1041170.0,MANHATTAN,10065.0,53,East 66th Street,1381,25,WTI0446001660,2021,1,...,40.767746,-73.967668,8.0,4.0,122.0,1.013810e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28,53 East 66th Street,53 east 66th street
3898,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI0492131353,2021,1,...,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:30,125 worth street,125 worth street
3953,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,2025-07-04 12:15:37,80 centre street,80 centre street
5067,1044738.0,MANHATTAN,10065.0,301,East 66th Street,1441,7501,WTI3342499907,2021,1,...,40.764846,-73.960789,8.0,5.0,118.0,1.014418e+09,Lenox Hill-Roosevelt Island,2025-07-04 12:15:30,301 East 66th Street,301 east 66th street
7867,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,1,...,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,2025-07-04 12:15:29,31 Chambers street,31 chambers street
10273,1041848.0,MANHATTAN,10075.0,969,Fifth Avenue,1392,69,WTI8826904066,2020,1,...,40.776111,-73.963992,8.0,4.0,142.0,1.013920e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26,969 Fifth Avenue,969 fifth avenue
17273,3001881.0,BROOKLYN,11201.0,45,monroe place,237,1,WTI5577496755,2021,1,...,40.695822,-73.992802,2.0,33.0,502.0,3.002370e+09,Brooklyn Heights-Cobble Hill,2025-07-04 12:15:28,45 monroe place,45 monroe place
17725,1046777.0,MANHATTAN,10028.0,1020,Fifth Avenue,1495,1,WTI2347475303,2021,1,...,40.779558,-73.961531,8.0,4.0,142.0,1.014950e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28,1020 Fifth Avenue,1020 fifth avenue
20394,1074157.0,MANHATTAN,10029.0,1220,Fifth Avenue,1609,1,WTI6586276748,2021,1,...,40.792438,-73.952448,11.0,8.0,168.0,1.016090e+09,East Harlem South,2025-07-04 12:15:30,1220 Fifth Avenue,1220 fifth avenue
23125,1077512.0,MANHATTAN,10002.0,160,Madison Street,255,1,WTI0692171448,2020,1,...,40.712488,-73.991924,3.0,1.0,6.0,1.002550e+09,Lower East Side,2025-07-04 12:15:22,160 Madison Street,160 madison street
42729,1046953.0,MANHATTAN,10128.0,47,East 88th Street,1500,20,WTI3885353468,2021,1,...,40.781980,-73.957410,8.0,4.0,15002.0,1.015000e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:28,47 East 88th Street,47 east 88th street
44880,1015067.0,MANHATTAN,10001.0,121,West 27th St,803,21,WTI0569540150,2022,1,...,40.745831,-73.991916,5.0,3.0,95.0,1.008030e+09,Midtown-Midtown South,2025-07-04 12:15:27,121 West 27th St,121 west 27th st

In [146]:
##119 tanks had sediment
df20tonow_dirty_nodupes.query("SI_RESULT_SEDIMENT=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
44,1051245.0,MANHATTAN,10028.0,120,East End Avenue,1582,23,WTI1374769686,2020,1,...,40.774474,-73.945518,8.0,5.0,14401.0,1.015820e+09,Yorkville,2025-07-04 12:15:28,120 East End Avenue,120 east end avenue
131,1076286.0,MANHATTAN,10065.0,44,East 67th Street,1381,7503,WTI7777679836,2022,1,...,40.768391,-73.967296,8.0,4.0,122.0,1.013818e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:42,44 East 67th Street,44 east 67th street
209,1042806.0,MANHATTAN,10021.0,140,East 72nd Street,1406,17,WTI2689639003,2022,1,...,40.770533,-73.962493,8.0,4.0,128.0,1.014060e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:41,140 East 72nd Street,140 east 72nd street
214,1044838.0,MANHATTAN,10021.0,331,East 70th Street,1445,14,WTI4248725498,2020,1,...,40.766925,-73.957950,8.0,5.0,126.0,1.014450e+09,Lenox Hill-Roosevelt Island,2025-07-04 12:15:21,331 East 70th Street,331 east 70th street
329,1046861.0,MANHATTAN,10028.0,1056,Fifth Avenue,1498,69,WTI7980345404,2020,1,...,40.782107,-73.959988,8.0,4.0,15002.0,1.014980e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26,1056 Fifth Avenue,1056 fifth avenue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49452,1048787.0,MANHATTAN,10028.0,201,East 86th Street,1532,1,WTI8320363906,2024,1,...,40.778688,-73.953642,8.0,5.0,14602.0,1.015320e+09,Yorkville,2025-07-04 12:15:22,201 East 86th Street,201 east 86th street
49580,4004872.0,QUEENS,11101.0,29-27,Queens plaza north,403,9,WTI0929598953,2020,1,...,40.749915,-73.936630,1.0,26.0,33.0,4.004030e+09,Queensbridge-Ravenswood-Long Island City,2025-07-04 12:15:32,29-27 Queens plaza north,29-27 queens plaza north
49750,1040542.0,MANHATTAN,10022.0,455,East 57th Street,1369,19,WTI1545885615,2020,1,...,40.757809,-73.961713,6.0,5.0,10601.0,1.013690e+09,Turtle Bay-East Midtown,2025-07-04 12:15:37,455 East 57th Street,455 east 57th street
51751,1041288.0,MANHATTAN,10065.0,875,Fifth Avenue,1383,69,WTI2072744173,2020,1,...,40.770247,-73.968630,8.0,4.0,122.0,1.013830e+09,Upper East Side-Carnegie Hill,2025-07-04 12:15:26,875 Fifth Avenue,875 fifth avenue
54398,1031113.0,MANHATTAN,10024.0,60,Riverside Drive,1186,52,WTI8312650066,2023,1,...,40.784314,-73.982938,7.0,6.0,167.0,1.011860e+09,Upper West Side,2025-07-04 12:15:32,60 Riverside Drive,60 riverside drive

In [148]:
## 2 tanks had coliform
df20tonow_dirty_nodupes.query("COLIFORM=='P'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
4202,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI0233832515,2022,1,...,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28,35 hale street,35 hale street
12925,3057474.0,BROOKLYN,11217.0,62,HANSON PLACE,2003,19,WTI5724184982,2023,1,...,40.685414,-73.975096,2.0,35.0,35.0,3.020030e+09,Fort Greene,2025-07-04 12:15:42,62 HANSON PLACE,62 hanson place

In [152]:
## 2 tanks had ecoli. #4202 had both
df20tonow_dirty_nodupes.query("ECOLI=='P'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE,ADDRESS,ADDRESS_NORM
4202,5127737.0,STATEN ISLAND,10307.0,35,hale street,8034,45,WTI0233832515,2022,1,...,40.514811,-74.236572,3.0,51.0,248.0,5.080340e+09,Charleston-Richmond Valley-Tottenville,2025-07-04 12:15:28,35 hale street,35 hale street
20838,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI1718389770,2021,1,...,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,2025-07-04 12:15:17,34-27 34th St,34-27 34th st

In [176]:
## re-import saved csv so that I can unilaterally define violations with "Violation", "Meets standards", or "Not recorded" for Datawrapper
DF_NODUPES_RENAMEDCOLUMNS = pd.read_csv("01.01.20-07.08.25_dirty_dropdupes.csv")

In [232]:
## there are 127 dirty tanks recorded between 2020 and present
DF_NODUPES_RENAMEDCOLUMNS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BIN                          127 non-null    int64
 1   BOROUGH                      127 non-null    object
 2   ZIP                          127 non-null    int64
 3   ADDRESS_NORM                 127 non-null    object
 4   CONFIRMATION_NUM             127 non-null    object
 5   REPORTING_YEAR               127 non-null    int64
 6   TANK_NUM                     127 non-null    int64
 7   INSPECTION_DATE              127 non-null    object
 8   SI_RESULT_SEDIMENT           127 non-null    object
 9   SI_RESULT_BIOLOGICAL_GROWTH  127 non-null    object
 10  SI_RESULT_DEBRIS_INSECTS     127 non-null    object
 11  SI_RESULT_RODENT_BIRD        127 non-null    object
 12  COLIFORM                     127 non-null    object
 13  ECOLI                        127 non-null    object
 14  LATITUDE                     127 non-null    float64
 15  LONGITUDE                    127 non-null    float64
 16  COMMUNITY_BOARD              127 non-null    int64
 17  COUNCIL_DISTRICT             127 non-null    int64
 18  CENSUS_TRACT                 127 non-null    int64
 19  BBL                          127 non-null    int64
 20  NTA                          127 non-null    object
 21  BATCH_DATE                   127 non-null    object
dtypes: float64(2), int64(8), object(12)
memory usage: 22.0+ KB

In [182]:
#112 of 127 tanks were in manhattan
DF_NODUPES_RENAMEDCOLUMNS.query("BOROUGH == 'MANHATTAN'")

,BIN,BOROUGH,ZIP,ADDRESS_NORM,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,INSPECTION_DATE,SI_RESULT_SEDIMENT,SI_RESULT_BIOLOGICAL_GROWTH,...,COLIFORM,ECOLI,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
0,1051245,MANHATTAN,10028,120 east end avenue,WTI1374769686,2020,1,7/6/20,Violation,Meets standards,...,Meets standards,Meets standards,40.774474,-73.945518,8,5,14401,1015820023,Yorkville,7/4/25 12:15
1,1076286,MANHATTAN,10065,44 east 67th street,WTI7777679836,2022,1,10/24/22,Violation,Meets standards,...,Meets standards,Meets standards,40.768391,-73.967296,8,4,122,1013817503,Upper East Side-Carnegie Hill,7/4/25 12:15
2,1042806,MANHATTAN,10021,140 east 72nd street,WTI2689639003,2022,1,8/2/22,Violation,Meets standards,...,Meets standards,Meets standards,40.770533,-73.962493,8,4,128,1014060017,Upper East Side-Carnegie Hill,7/4/25 12:15
3,1044838,MANHATTAN,10021,331 east 70th street,WTI4248725498,2020,1,10/5/20,Violation,Meets standards,...,Meets standards,Meets standards,40.766925,-73.957950,8,5,126,1014450014,Lenox Hill-Roosevelt Island,7/4/25 12:15
4,1046861,MANHATTAN,10028,1056 fifth avenue,WTI7980345404,2020,1,6/24/20,Violation,Meets standards,...,Meets standards,Meets standards,40.782107,-73.959988,8,4,15002,1014980069,Upper East Side-Carnegie Hill,7/4/25 12:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,1015067,MANHATTAN,10001,121 west 27th st,WTI0569540150,2022,1,7/11/22,Violation,Violation,...,Meets standards,Meets standards,40.745831,-73.991916,5,3,95,1008030021,Midtown-Midtown South,7/4/25 12:15
122,1048787,MANHATTAN,10028,201 east 86th street,WTI8320363906,2024,1,9/24/24,Violation,Meets standards,...,Meets standards,Meets standards,40.778688,-73.953642,8,5,14602,1015320001,Yorkville,7/4/25 12:15
124,1040542,MANHATTAN,10022,455 east 57th street,WTI1545885615,2020,1,10/21/20,Violation,Meets standards,...,Meets standards,Meets standards,40.757809,-73.961713,6,5,10601,1013690019,Turtle Bay-East Midtown,7/4/25 12:15
125,1041288,MANHATTAN,10065,875 fifth avenue,WTI2072744173,2020,1,9/16/20,Violation,Meets standards,...,Meets standards,Meets standards,40.770247,-73.968630,8,4,122,1013830069,Upper East Side-Carnegie Hill,7/4/25 12:15
126,1031113,MANHATTAN,10024,60 riverside drive,WTI8312650066,2023,1,10/31/23,Violation,Meets standards,...,Meets standards,Meets standards,40.784314,-73.982938,7,6,167,1011860052,Upper West Side,7/4/25 12:15

AUDIT ANALYSIS

In [187]:
## audits are only updated from 2021 to 3/11/24
df_audits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16564 entries, 0 to 16563
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   BIN                 16561 non-null  float64
 1   House #             16560 non-null  object
 2   Street Name         16561 non-null  object
 3   Zip_code            16561 non-null  object
 4   Borough             16561 non-null  object
 5   Status              16561 non-null  object
 6   Number of DWT       16561 non-null  float64
 7   Activity_Type       16561 non-null  object
 8   Activity_Year       16561 non-null  float64
 9   Violation_Code      1414 non-null   object
 10  Law_Section         1414 non-null   object
 11  Violation_Text      1414 non-null   object
 12  Compliance_Year     16555 non-null  float64
 13  Date_of_Occurrence  1412 non-null   datetime64[ns]
 14  Summons_Number      1349 non-null   float64
 15  BBL                 16559 non-null  float64
 16  Longitude           16562 non-null  float64
 17  Latitude            16561 non-null  float64
 18  Community_Board     16561 non-null  float64
 19  Council_District    16561 non-null  float64
 20  Census_Tract        16561 non-null  float64
 21  NTA_Code            16561 non-null  object
dtypes: datetime64[ns](1), float64(11), object(10)
memory usage: 2.8+ MB

In [191]:
##normalize addresses like in water tank data
df_audits['ADDRESS'] = df_audits['House #'].astype(str)+ ' ' + df_audits['Street Name'].astype(str)

In [193]:
df_audits['ADDRESS_NORM'] = df_audits['ADDRESS'].str.lower().str.strip()

In [207]:
df_audits_sortedAddress = df_audits.sort_values('Date_of_Occurrence', ascending=False)

In [209]:
##sort by BIN number in order to drop all less-recent records
df_audits_sortedBIN = df_audits_sortedAddress.sort_values('BIN', ascending=False)

In [211]:
df_audits_DroppedDupeBIN = df_audits_sortedBIN.drop_duplicates(subset='BIN')

In [213]:
df_audits_DroppedDupeBIN.sample(5)

,BIN,House #,Street Name,Zip_code,Borough,Status,Number of DWT,Activity_Type,Activity_Year,Violation_Code,...,Summons_Number,BBL,Longitude,Latitude,Community_Board,Council_District,Census_Tract,NTA_Code,ADDRESS,ADDRESS_NORM
12715,1016900.0,79,MADISON AVENUE,10016,MANHATTAN,Active,1.0,Self-Reported Annual Inspection,2023.0,NaN,...,NaN,1.008580e+09,-73.985619,40.744096,105.0,2.0,7400.0,MN0501,79 MADISON AVENUE,79 madison avenue
8856,1041137.0,630,Park Avenue,10065,Manhattan,Active,1.0,Self-Reported Annual Inspection,2022.0,NaN,...,NaN,1.013800e+09,-73.966780,40.767071,108.0,4.0,12200.0,MN0802,630 Park Avenue,630 park avenue
3898,1041317.0,28,East 70 Street,10021,Manhattan,Active,1.0,Self-Reported Annual Inspection,2021.0,NaN,...,NaN,1.013848e+09,-73.966168,40.770375,108.0,4.0,12200.0,MN0802,28 East 70 Street,28 east 70 street
15662,1087937.0,40,EAST 66 STREET,10065,MANHATTAN,Active,1.0,Self-Reported Annual Inspection,2023.0,NaN,...,NaN,1.013808e+09,-73.967841,40.767801,108.0,4.0,12200.0,MN0802,40 EAST 66 STREET,40 east 66 street
3820,1040542.0,455,East 57 Street,10022,Manhattan,Active,1.0,Self-Reported Annual Inspection,2021.0,NaN,...,NaN,1.013690e+09,-73.961713,40.757809,106.0,4.0,10601.0,MN0604,455 East 57 Street,455 east 57 street

In [223]:
## remove xtra columns not needed
df_audits_DroppedDupeBIN_NoExtraCols = df_audits_DroppedDupeBIN.drop(['House #', 'Street Name', 'ADDRESS'], axis=1)

In [225]:
df_audits_DroppedDupeBIN_NoExtraCols = df_audits_DroppedDupeBIN_NoExtraCols.reset_index(drop=True)

In [230]:
## there have been 5402 audit logs between 2021 to 3/11/24
df_audits_DroppedDupeBIN_NoExtraCols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5403 entries, 0 to 5402
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   BIN                 5402 non-null   float64
 1   Zip_code            5402 non-null   object
 2   Borough             5402 non-null   object
 3   Status              5402 non-null   object
 4   Number of DWT       5402 non-null   float64
 5   Activity_Type       5402 non-null   object
 6   Activity_Year       5402 non-null   float64
 7   Violation_Code      413 non-null    object
 8   Law_Section         413 non-null    object
 9   Violation_Text      413 non-null    object
 10  Compliance_Year     5402 non-null   float64
 11  Date_of_Occurrence  412 non-null    datetime64[ns]
 12  Summons_Number      395 non-null    float64
 13  BBL                 5401 non-null   float64
 14  Longitude           5402 non-null   float64
 15  Latitude            5402 non-null   float64
 16  Community_Board     5402 non-null   float64
 17  Council_District    5402 non-null   float64
 18  Census_Tract        5402 non-null   float64
 19  NTA_Code            5402 non-null   object
 20  ADDRESS_NORM        5403 non-null   object
dtypes: datetime64[ns](1), float64(11), object(9)
memory usage: 886.6+ KB

In [234]:
df_merged = pd.merge(df_audits_DroppedDupeBIN_NoExtraCols, DF_NODUPES_RENAMEDCOLUMNS, on='BIN', how='outer', indicator=True)

In [236]:
df_merged.sample(2)

,BIN,Zip_code,Borough,Status,Number of DWT,Activity_Type,Activity_Year,Violation_Code,Law_Section,Violation_Text,...,ECOLI,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL_y,NTA,BATCH_DATE,_merge
3977,1081252.0,10021,Manhattan,Active,13.0,Self-Reported Annual Inspection,2021.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4677,2091961.0,10456,Bronx,Active,1.0,Self-Reported Annual Inspection,2021.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [238]:
df_merged.to_csv("07.08_merged water tank audits and reports.csv")

In [ ]:
## when merged, 125 water tanks are in both sets. assuming that all self-reported water tank inspections were in the audit report