In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("Self-Reported_Drinking_Water_Tank_Inspection_Results_20250408.csv")

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55707 entries, 0 to 55706
Data columns (total 49 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   BIN                           55616 non-null  float64
 1   BOROUGH                       55707 non-null  object
 2   ZIP                           55629 non-null  float64
 3   HOUSE_NUM                     55707 non-null  object
 4   STREET_NAME                   55707 non-null  object
 5   BLOCK                         55707 non-null  int64
 6   LOT                           55707 non-null  int64
 7   CONFIRMATION_NUM              55707 non-null  object
 8   REPORTING_YEAR                55707 non-null  int64
 9   TANK_NUM                      55707 non-null  int64
 10  INSPECTION_BY_FIRM            55685 non-null  object
 11  INSPECTION_PERFORMED          55707 non-null  object
 12  INSPECTION_DATE               55685 non-null  object
 13  GI_REQ_INTERNAL_STRUCTURE     55707 non-null  object
 14  GI_RESULT_INTERNAL_STRUCTURE  55610 non-null  object
 15  GI_REQ_EXTERNAL_STRUCTURE     55707 non-null  object
 16  GI_RESULT_EXTERNAL_STRUCTURE  55649 non-null  object
 17  GI_REQ_OVERFLOW_PIPES         55707 non-null  object
 18  GI_RESULT_OVERFLOW_PIPES      55648 non-null  object
 19  GI_REQ_ACCESS_LADDERS         55707 non-null  object
 20  GI_RESULT_ACCESS_LADDERS      55598 non-null  object
 21  GI_REQ_AIR_VENTS              55707 non-null  object
 22  GI_RESULT_AIR_VENTS           55653 non-null  object
 23  GI_REQ_ROOF_ACCESS            55707 non-null  object
 24  GI_RESULT_ROOF_ACCESS         55578 non-null  object
 25  SI_REQ_SEDIMENT               55707 non-null  object
 26  SI_RESULT_SEDIMENT            55605 non-null  object
 27  SI_REQ_BIOLOGICAL_GROWTH      55707 non-null  object
 28  SI_RESULT_BIOLOGICAL_GROWTH   55604 non-null  object
 29  SI_REQ_DEBRIS_INSECTS         55707 non-null  object
 30  SI_RESULT_DEBRIS_INSECTS      55603 non-null  object
 31  SI_REQ_RODENT_BIRD            55707 non-null  object
 32  SI_RESULT_RODENT_BIRD         55645 non-null  object
 33  SAMPLE_COLLECTED              55701 non-null  object
 34  LAB_NAME                      55590 non-null  object
 35  NYS_CERTIFIED                 55593 non-null  object
 36  ANALYTES                      55597 non-null  object
 37  COLIFORM                      55571 non-null  object
 38  ECOLI                         55571 non-null  object
 39  MEET_STANDARDS                11127 non-null  object
 40  DELETED                       55707 non-null  object
 41  LATITUDE                      55602 non-null  float64
 42  LONGITUDE                     55602 non-null  float64
 43  COMMUNITY_BOARD               55602 non-null  float64
 44  COUNCIL_DISTRICT              55602 non-null  float64
 45  CENSUS_TRACT                  55602 non-null  float64
 46  BBL                           55560 non-null  float64
 47  NTA                           55602 non-null  object
 48  BATCH_DATE                    55707 non-null  object
dtypes: float64(8), int64(4), object(37)
memory usage: 20.8+ MB

In [88]:
df.query("SI_RESULT_BIOLOGICAL_GROWTH == 'A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
390,1074157.0,MANHATTAN,10029.0,1220,Fifth Avenue,1609,1,WTI3318732840,2021,1,...,NaN,No,40.792438,-73.952448,11.0,8.0,168.0,1.016090e+09,East Harlem South,04/04/2025 12:15:26 PM
593,1040884.0,MANHATTAN,10065.0,812,Fifth Avenue,1377,3,WTI5225782252,2015,1,...,NaN,No,40.766378,-73.971459,8.0,4.0,11401.0,1.013770e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:09 PM
605,1046953.0,MANHATTAN,10128.0,47,East 88th Street,1500,20,WTI3885353468,2021,1,...,NaN,No,40.781980,-73.957410,8.0,4.0,15002.0,1.015000e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:26 PM
1619,1051245.0,MANHATTAN,10028.0,120,East End Avenue,1582,23,WTI7873727524,2015,1,...,NaN,No,40.774474,-73.945518,8.0,5.0,14401.0,1.015820e+09,Yorkville,04/04/2025 12:15:09 PM
1786,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI9685378701,2020,1,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,04/04/2025 12:15:35 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52025,1077512.0,MANHATTAN,10002.0,160,Madison Street,255,1,WTI0692171448,2020,1,...,NaN,No,40.712488,-73.991924,3.0,1.0,6.0,1.002550e+09,Lower East Side,04/04/2025 12:15:20 PM
52464,1038770.0,MANHATTAN,10017.0,310,East 46th Street,1338,5,WTI4477195314,2020,1,...,NaN,No,40.752154,-73.969834,6.0,4.0,90.0,1.013380e+09,Turtle Bay-East Midtown,04/04/2025 12:15:24 PM
54722,1038645.0,MANHATTAN,10016.0,305,East 40th Street,1333,1,WTI7127696291,2021,1,...,NaN,No,40.748469,-73.972954,6.0,4.0,88.0,1.013330e+09,Turtle Bay-East Midtown,04/04/2025 12:15:26 PM
54869,3048341.0,BROOKLYN,11206.0,760,Broadway,1723,1,WTI4188377400,2018,1,...,NaN,No,40.700528,-73.941604,3.0,36.0,28501.0,3.017230e+09,Bushwick South,04/04/2025 12:15:22 PM
55628,1040543.0,MANHATTAN,10022.0,4,Sutton Place,1369,24,WTI8716577061,2020,1,...,NaN,No,40.757512,-73.960576,6.0,5.0,10601.0,1.013690e+09,Turtle Bay-East Midtown,04/04/2025 12:15:24 PM

In [86]:
## 237 tanks have unacceptable internal or external structure
df.query("(GI_RESULT_INTERNAL_STRUCTURE=='A') or (GI_RESULT_EXTERNAL_STRUCTURE=='A')")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
96,1088469.0,MANHATTAN,10007.0,One,One World Trade Center,58,1,WTI4725294684,2015,2,...,NaN,No,40.713099,-74.013062,1.0,1.0,13.0,1.000580e+09,Battery Park City-Lower Manhattan,04/04/2025 12:15:09 PM
188,1077418.0,MANHATTAN,10038.0,15,Saint james Place,111,100,WTI0963545923,2019,1,...,NaN,No,40.711571,-73.999903,3.0,1.0,25.0,1.001110e+09,Chinatown,04/04/2025 12:15:23 PM
222,1038645.0,MANHATTAN,10016.0,305,East 40th Street,1333,1,WTI5909529509,2017,1,...,NaN,No,40.748469,-73.972954,6.0,4.0,88.0,1.013330e+09,Turtle Bay-East Midtown,04/04/2025 12:15:16 PM
439,1079000.0,MANHATTAN,10013.0,100,Centre street,167,1,WTI8575169124,2023,2,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,04/04/2025 12:15:40 PM
1161,1077512.0,MANHATTAN,10002.0,160,Madison Street,255,1,WTI1217683859,2019,1,...,NaN,No,40.712488,-73.991924,3.0,1.0,6.0,1.002550e+09,Lower East Side,04/04/2025 12:15:36 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55085,3392969.0,BROOKLYN,11201.0,345,Adams street,140,7503,WTI2406385033,2024,1,...,NaN,No,40.693400,-73.988915,2.0,33.0,11.0,3.001408e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,04/04/2025 12:15:32 PM
55117,1053899.0,MANHATTAN,10037.0,506,Lenox Avenue,1733,1,WTI5388140760,2018,2,...,NaN,No,40.814358,-73.940659,10.0,9.0,212.0,1.017330e+09,Central Harlem North-Polo Grounds,04/04/2025 12:15:24 PM
55122,3392969.0,BROOKLYN,11201.0,345,adams street,140,7503,WTI7595330212,2021,3,...,NaN,No,40.693400,-73.988915,2.0,33.0,11.0,3.001408e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,04/04/2025 12:15:26 PM
55219,3325168.0,BROOKLYN,11233.0,311,Patchen Avenue,1688,1,WTI2298617382,2019,1,...,NaN,No,40.680567,-73.925559,3.0,41.0,381.0,3.016880e+09,Crown Heights North,04/04/2025 12:15:36 PM
55359,3002558.0,BROOKLYN,11201.0,210,Joralemon street,266,7501,WTI3648401284,2022,1,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,04/04/2025 12:15:26 PM

In [12]:
standards = df["MEET_STANDARDS"]

In [14]:
standards.describe()

count     11127
unique        2
top           Y
freq      11116
Name: MEET_STANDARDS, dtype: object

In [38]:
bacteriadf = df.query("(COLIFORM=='P') or (ECOLI=='P')")

In [56]:
## 213 water tanks have insect debris
df.query("SI_RESULT_DEBRIS_INSECTS=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
593,1040884.0,MANHATTAN,10065.0,812,Fifth Avenue,1377,3,WTI5225782252,2015,1,...,NaN,No,40.766378,-73.971459,8.0,4.0,11401.0,1.013770e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:09 PM
706,1086515.0,MANHATTAN,10016.0,462,First Avenue,962,100,WTI2954106793,2017,3,...,NaN,No,40.739497,-73.976624,6.0,4.0,62.0,1.009620e+09,Murray Hill-Kips Bay,04/04/2025 12:15:17 PM
820,3251647.0,BROOKLYN,11205.0,100,North Portland Avenue,2039,101,WTI3729874771,2017,4,...,NaN,No,40.695268,-73.976232,2.0,35.0,2901.0,3.020390e+09,Fort Greene,04/04/2025 12:15:17 PM
1550,1001241.0,MANHATTAN,10007.0,225,Broadway,88,18,WTI5030597317,2015,4,...,NaN,No,40.711870,-74.008217,1.0,1.0,21.0,1.000880e+09,SoHo-TriBeCa-Civic Center-Little Italy,04/04/2025 12:15:14 PM
1604,2013245.0,BRONX,10460.0,1010,East 178th Street,3130,100,WTI0141494333,2019,1,...,NaN,No,40.841412,-73.880463,6.0,15.0,361.0,2.031300e+09,East Tremont,04/04/2025 12:15:20 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54010,1079000.0,MANHATTAN,10013.0,100,Centre Street,167,1,WTI2666744471,2022,2,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,04/04/2025 12:15:26 PM
54285,1079000.0,MANHATTAN,10013.0,100,Centre Street,167,1,WTI7177028402,2022,2,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,04/04/2025 12:15:25 PM
54620,4437132.0,QUEENS,11373.0,79-01,Broadway,1500,2,WTI2542780195,2015,3,...,NaN,No,40.744416,-73.886097,4.0,25.0,267.0,4.015000e+09,Elmhurst,04/04/2025 12:15:18 PM
55431,1081771.0,MANHATTAN,10023.0,40-50,Amsterdam Avenue,1154,101,WTI6852338559,2019,1,...,NaN,No,40.771703,-73.986685,7.0,6.0,151.0,1.011540e+09,Lincoln Square,04/04/2025 12:15:36 PM
55614,3396962.0,BROOKLYN,11201.0,138,Willoughby Street,149,1,WTI0365167644,2022,4,...,NaN,No,40.692069,-73.983135,2.0,33.0,15.0,3.001498e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,04/04/2025 12:15:33 PM

In [52]:
## 226 water tanks have rodent,bird, or insect debris
df.query("(SI_RESULT_RODENT_BIRD=='A') or (SI_RESULT_DEBRIS_INSECTS=='A')")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
593,1040884.0,MANHATTAN,10065.0,812,Fifth Avenue,1377,3,WTI5225782252,2015,1,...,NaN,No,40.766378,-73.971459,8.0,4.0,11401.0,1.013770e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:09 PM
706,1086515.0,MANHATTAN,10016.0,462,First Avenue,962,100,WTI2954106793,2017,3,...,NaN,No,40.739497,-73.976624,6.0,4.0,62.0,1.009620e+09,Murray Hill-Kips Bay,04/04/2025 12:15:17 PM
820,3251647.0,BROOKLYN,11205.0,100,North Portland Avenue,2039,101,WTI3729874771,2017,4,...,NaN,No,40.695268,-73.976232,2.0,35.0,2901.0,3.020390e+09,Fort Greene,04/04/2025 12:15:17 PM
1550,1001241.0,MANHATTAN,10007.0,225,Broadway,88,18,WTI5030597317,2015,4,...,NaN,No,40.711870,-74.008217,1.0,1.0,21.0,1.000880e+09,SoHo-TriBeCa-Civic Center-Little Italy,04/04/2025 12:15:14 PM
1604,2013245.0,BRONX,10460.0,1010,East 178th Street,3130,100,WTI0141494333,2019,1,...,NaN,No,40.841412,-73.880463,6.0,15.0,361.0,2.031300e+09,East Tremont,04/04/2025 12:15:20 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54010,1079000.0,MANHATTAN,10013.0,100,Centre Street,167,1,WTI2666744471,2022,2,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,04/04/2025 12:15:26 PM
54285,1079000.0,MANHATTAN,10013.0,100,Centre Street,167,1,WTI7177028402,2022,2,...,NaN,No,40.716084,-74.001425,1.0,1.0,29.0,1.001670e+09,Chinatown,04/04/2025 12:15:25 PM
54620,4437132.0,QUEENS,11373.0,79-01,Broadway,1500,2,WTI2542780195,2015,3,...,NaN,No,40.744416,-73.886097,4.0,25.0,267.0,4.015000e+09,Elmhurst,04/04/2025 12:15:18 PM
55431,1081771.0,MANHATTAN,10023.0,40-50,Amsterdam Avenue,1154,101,WTI6852338559,2019,1,...,NaN,No,40.771703,-73.986685,7.0,6.0,151.0,1.011540e+09,Lincoln Square,04/04/2025 12:15:36 PM
55614,3396962.0,BROOKLYN,11201.0,138,Willoughby Street,149,1,WTI0365167644,2022,4,...,NaN,No,40.692069,-73.983135,2.0,33.0,15.0,3.001498e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,04/04/2025 12:15:33 PM

In [64]:
df[(df["INSPECTION_DATE"] >= "2020-01-01") & (df["INSPECTION_DATE"] <= "2025-04-08")]

Empty DataFrame
Columns: [BIN, BOROUGH, ZIP, HOUSE_NUM, STREET_NAME, BLOCK, LOT, CONFIRMATION_NUM, REPORTING_YEAR, TANK_NUM, INSPECTION_BY_FIRM, INSPECTION_PERFORMED, INSPECTION_DATE, GI_REQ_INTERNAL_STRUCTURE, GI_RESULT_INTERNAL_STRUCTURE, GI_REQ_EXTERNAL_STRUCTURE, GI_RESULT_EXTERNAL_STRUCTURE, GI_REQ_OVERFLOW_PIPES, GI_RESULT_OVERFLOW_PIPES, GI_REQ_ACCESS_LADDERS, GI_RESULT_ACCESS_LADDERS, GI_REQ_AIR_VENTS, GI_RESULT_AIR_VENTS, GI_REQ_ROOF_ACCESS, GI_RESULT_ROOF_ACCESS, SI_REQ_SEDIMENT, SI_RESULT_SEDIMENT, SI_REQ_BIOLOGICAL_GROWTH, SI_RESULT_BIOLOGICAL_GROWTH, SI_REQ_DEBRIS_INSECTS, SI_RESULT_DEBRIS_INSECTS, SI_REQ_RODENT_BIRD, SI_RESULT_RODENT_BIRD, SAMPLE_COLLECTED, LAB_NAME, NYS_CERTIFIED, ANALYTES, COLIFORM, ECOLI, MEET_STANDARDS, DELETED, LATITUDE, LONGITUDE, COMMUNITY_BOARD, COUNCIL_DISTRICT, CENSUS_TRACT, BBL, NTA, BATCH_DATE]
Index: []

[0 rows x 49 columns]

In [54]:
## 42 tanks have rodent or bird poop
df.query("SI_RESULT_RODENT_BIRD=='A'")

,BIN,BOROUGH,ZIP,HOUSE_NUM,STREET_NAME,BLOCK,LOT,CONFIRMATION_NUM,REPORTING_YEAR,TANK_NUM,...,MEET_STANDARDS,DELETED,LATITUDE,LONGITUDE,COMMUNITY_BOARD,COUNCIL_DISTRICT,CENSUS_TRACT,BBL,NTA,BATCH_DATE
593,1040884.0,MANHATTAN,10065.0,812,Fifth Avenue,1377,3,WTI5225782252,2015,1,...,NaN,No,40.766378,-73.971459,8.0,4.0,11401.0,1.013770e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:09 PM
5113,3323300.0,BROOKLYN,11217.0,198,Bond Street,392,1,WTI9443315641,2019,1,...,NaN,No,40.683171,-73.987413,6.0,33.0,71.0,3.003920e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,04/04/2025 12:15:36 PM
7485,1034324.0,MANHATTAN,10036.0,33,West 46th street,1262,21,WTI1383732606,2015,1,...,NaN,No,40.756553,-73.980242,5.0,4.0,96.0,1.012620e+09,Midtown-Midtown South,04/04/2025 12:15:13 PM
7521,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI6999130303,2021,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,04/04/2025 12:15:26 PM
7648,1048136.0,MANHATTAN,10128.0,1111,park ave,1518,69,WTI7707268859,2015,1,...,NaN,No,40.782473,-73.955513,8.0,4.0,14802.0,1.015180e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:13 PM
9675,1041332.0,MANHATTAN,10021.0,720,Park Avenue,1385,32,WTI6304305629,2021,1,...,NaN,No,40.769950,-73.964681,8.0,4.0,130.0,1.013850e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:28 PM
11078,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,2,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,04/04/2025 12:15:33 PM
11368,1048136.0,MANHATTAN,10128.0,1111,park ave,1518,69,WTI7707268859,2015,2,...,NaN,No,40.782473,-73.955513,8.0,4.0,14802.0,1.015180e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:14 PM
13783,1084520.0,MANHATTAN,10039.0,2971,Frederick Douglas Boulevard,2106,3,WTI2294705578,2019,1,...,NaN,No,40.830297,-73.936456,10.0,9.0,24302.0,1.021060e+09,Central Harlem North-Polo Grounds,04/04/2025 12:15:36 PM
14679,1084673.0,MANHATTAN,10019.0,15,West 56th Street,1272,26,WTI7792919211,2021,1,...,NaN,No,40.762640,-73.975258,5.0,4.0,11201.0,1.012720e+09,Midtown-Midtown South,04/04/2025 12:15:19 PM
15944,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,3,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,04/04/2025 12:15:33 PM
17254,3336073.0,BROOKLYN,11217.0,426,Baltic Street,404,1,WTI7056373565,2019,1,...,NaN,No,40.683555,-73.988552,6.0,33.0,71.0,3.004040e+09,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,04/04/2025 12:15:36 PM
20014,1041333.0,MANHATTAN,10021.0,730,Park Avenue,1385,37,WTI6324726286,2017,1,...,NaN,No,40.770553,-73.964897,8.0,4.0,130.0,1.013850e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:11 PM
20751,1077376.0,MANHATTAN,10035.0,1879,Madison Avenue,1747,35,WTI3110930977,2018,1,...,NaN,No,40.803610,-73.942250,11.0,9.0,198.0,1.017470e+09,East Harlem North,04/04/2025 12:15:22 PM
21384,3327711.0,BROOKLYN,11203.0,451,Clarkson Avenue,4829,1,WTI5396803490,2018,7,...,NaN,No,40.655760,-73.944602,9.0,40.0,808.0,3.048290e+09,Prospect Lefferts Gardens-Wingate,04/04/2025 12:15:17 PM
21711,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI7080721393,2020,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,04/04/2025 12:15:33 PM
22144,1078858.0,MANHATTAN,10029.0,70,East 108th Street,1613,23,WTI3538482346,2020,2,...,NaN,No,40.794429,-73.947434,11.0,8.0,17401.0,1.016130e+09,East Harlem South,04/04/2025 12:15:20 PM
24936,1027087.0,MANHATTAN,10036.0,520,12th Ave,1090,1,WTI9977468480,2021,1,...,NaN,No,40.762316,-74.000036,4.0,3.0,129.0,1.010900e+09,Clinton,04/04/2025 12:15:24 PM
27067,3002558.0,BROOKLYN,11201.0,210,Joralemon Street,266,7501,WTI0157464748,2020,1,...,NaN,No,40.692459,-73.990491,2.0,33.0,9.0,3.002668e+09,Brooklyn Heights-Cobble Hill,04/04/2025 12:15:33 PM
27669,1048136.0,MANHATTAN,10128.0,1111,park ave,1518,69,WTI7707268859,2015,4,...,NaN,No,40.782473,-73.955513,8.0,4.0,14802.0,1.015180e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:12 PM
28296,1001830.0,MANHATTAN,10013.0,80,centre street,166,27,WTI6104334177,2020,1,...,NaN,No,40.715447,-74.001890,1.0,1.0,29.0,1.001660e+09,Chinatown,04/04/2025 12:15:35 PM
28396,3321615.0,BROOKLYN,11224.0,2839,West 33rd Street,7007,1,WTI6406059648,2019,1,...,NaN,No,40.576306,-73.999849,13.0,47.0,328.0,3.070070e+09,Seagate-Coney Island,04/04/2025 12:15:35 PM
28586,1077512.0,MANHATTAN,10002.0,160,Madison Street,255,1,WTI0692171448,2020,2,...,NaN,No,40.712488,-73.991924,3.0,1.0,6.0,1.002550e+09,Lower East Side,04/04/2025 12:15:20 PM
31358,1031729.0,MANHATTAN,10025.0,12,West 96th Street,1209,37,WTI1089994637,2017,1,...,NaN,No,40.791880,-73.965222,7.0,6.0,181.0,1.012090e+09,Upper West Side,04/04/2025 12:15:11 PM
31616,1001831.0,MANHATTAN,10013.0,125,worth street,168,32,WTI9685378701,2020,2,...,NaN,No,40.715428,-74.002673,1.0,1.0,31.0,1.001680e+09,SoHo-TriBeCa-Civic Center-Little Italy,04/04/2025 12:15:35 PM
32752,1078033.0,MANHATTAN,10002.0,80-90,Baruch Drive,323,1,WTI7374795312,2019,2,...,NaN,No,40.717693,-73.978081,3.0,2.0,1002.0,1.003230e+09,Lower East Side,04/04/2025 12:15:36 PM
34146,1041332.0,MANHATTAN,10021.0,720,Park Avenue,1385,32,WTI7305156430,2021,1,...,NaN,No,40.769950,-73.964681,8.0,4.0,130.0,1.013850e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:26 PM
37397,1083929.0,MANHATTAN,10029.0,1901,First Avenue,1669,1,WTI1578697805,2016,1,...,NaN,No,40.784557,-73.943780,11.0,8.0,15602.0,1.016690e+09,East Harlem South,04/04/2025 12:15:17 PM
39935,1048523.0,MANHATTAN,10075.0,201,East 80th Street,1526,7501,WTI7820938550,2017,1,...,NaN,No,40.774832,-73.956454,8.0,5.0,138.0,1.015268e+09,Yorkville,04/04/2025 12:15:12 PM
40835,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI0744599622,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,04/04/2025 12:15:16 PM
41302,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,2,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,04/04/2025 12:15:27 PM
41758,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI2400327671,2020,2,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,04/04/2025 12:15:27 PM
41864,1078858.0,MANHATTAN,10029.0,70,East 108th Street,1613,23,WTI3538482346,2020,1,...,NaN,No,40.794429,-73.947434,11.0,8.0,17401.0,1.016130e+09,East Harlem South,04/04/2025 12:15:20 PM
43057,4009619.0,QUEENS,11106.0,34-27,34th St,642,18,WTI2022892081,2021,1,...,N,Yes,40.758027,-73.925263,1.0,26.0,57.0,4.006420e+09,Astoria,04/04/2025 12:15:19 PM
44674,1035435.0,MANHATTAN,10017.0,17E,48TH STREET,1284,12,WTI8564522198,2015,1,...,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/04/2025 12:15:09 PM
45409,1034496.0,MANHATTAN,10036.0,38W,48TH STREET,1263,58,WTI4668337261,2015,1,...,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/04/2025 12:15:13 PM
47494,1048136.0,MANHATTAN,10128.0,1111,park ave,1518,69,WTI7707268859,2015,3,...,NaN,No,40.782473,-73.955513,8.0,4.0,14802.0,1.015180e+09,Upper East Side-Carnegie Hill,04/04/2025 12:15:11 PM
48033,1051954.0,MANHATTAN,10029.0,1405,Park Avenue,1632,1,WTI4248989974,2019,1,...,NaN,No,40.791797,-73.948703,11.0,8.0,166.0,1.016320e+09,East Harlem South,04/04/2025 12:15:35 PM
48131,3189556.0,BROOKLYN,11224.0,2007,Surf Avenue,7059,26,WTI7216430331,2019,1,...,NaN,No,40.574792,-73.986991,13.0,47.0,326.0,3.070590e+09,Seagate-Coney Island,04/04/2025 12:15:36 PM
50664,2101266.0,BRONX,10456.0,1118,Grand Concourse,2462,39,WTI4354141630,2021,1,...,NaN,No,40.832232,-73.919655,4.0,16.0,18102.0,2.024620e+09,East Concourse-Concourse Village,04/04/2025 12:15:27 PM
51515,1001670.0,MANHATTAN,10007.0,31,Chambers street,153,24,WTI4957674766,2021,1,...,NaN,No,40.713402,-74.004635,1.0,1.0,31.0,1.001530e+09,SoHo-TriBeCa-Civic Center-Little Italy,04/04/2025 12:15:27 PM
51924,3321771.0,BROOKLYN,11224.0,2940,West 31st Street,7049,15,WTI2718924488,2019,1,...,NaN,No,40.574480,-73.997372,13.0,47.0,342.0,3.070490e+09,Seagate-Coney Island,04/04/2025 12:15:36 PM

In [46]:
bacteriadf["ZIP"].unique()

array([11238., 10307., 10013., 11201., 10461., 11106., 11101., 11217.,
       10023., 10031.])

In [48]:
bacteriadf.count()

BIN                             25
BOROUGH                         25
ZIP                             25
HOUSE_NUM                       25
STREET_NAME                     25
BLOCK                           25
LOT                             25
CONFIRMATION_NUM                25
REPORTING_YEAR                  25
TANK_NUM                        25
INSPECTION_BY_FIRM              25
INSPECTION_PERFORMED            25
INSPECTION_DATE                 25
GI_REQ_INTERNAL_STRUCTURE       25
GI_RESULT_INTERNAL_STRUCTURE    23
GI_REQ_EXTERNAL_STRUCTURE       25
GI_RESULT_EXTERNAL_STRUCTURE    22
GI_REQ_OVERFLOW_PIPES           25
GI_RESULT_OVERFLOW_PIPES        22
GI_REQ_ACCESS_LADDERS           25
GI_RESULT_ACCESS_LADDERS        21
GI_REQ_AIR_VENTS                25
GI_RESULT_AIR_VENTS             23
GI_REQ_ROOF_ACCESS              25
GI_RESULT_ROOF_ACCESS           23
SI_REQ_SEDIMENT                 25
SI_RESULT_SEDIMENT              22
SI_REQ_BIOLOGICAL_GROWTH        25
SI_RESULT_BIOLOGICAL_GROWTH     19
SI_REQ_DEBRIS_INSECTS           25
SI_RESULT_DEBRIS_INSECTS        23
SI_REQ_RODENT_BIRD              25
SI_RESULT_RODENT_BIRD           19
SAMPLE_COLLECTED                25
LAB_NAME                        25
NYS_CERTIFIED                   25
ANALYTES                        25
COLIFORM                        25
ECOLI                           25
MEET_STANDARDS                   3
DELETED                         25
LATITUDE                        25
LONGITUDE                       25
COMMUNITY_BOARD                 25
COUNCIL_DISTRICT                25
CENSUS_TRACT                    25
BBL                             25
NTA                             25
BATCH_DATE                      25
dtype: int64

In [24]:
dnmeet = df.query("MEET_STANDARDS == 'N'")

In [30]:
dnmeet.count()

BIN                             11
BOROUGH                         11
ZIP                             11
HOUSE_NUM                       11
STREET_NAME                     11
BLOCK                           11
LOT                             11
CONFIRMATION_NUM                11
REPORTING_YEAR                  11
TANK_NUM                        11
INSPECTION_BY_FIRM              11
INSPECTION_PERFORMED            11
INSPECTION_DATE                 11
GI_REQ_INTERNAL_STRUCTURE       11
GI_RESULT_INTERNAL_STRUCTURE     7
GI_REQ_EXTERNAL_STRUCTURE       11
GI_RESULT_EXTERNAL_STRUCTURE     6
GI_REQ_OVERFLOW_PIPES           11
GI_RESULT_OVERFLOW_PIPES         8
GI_REQ_ACCESS_LADDERS           11
GI_RESULT_ACCESS_LADDERS         7
GI_REQ_AIR_VENTS                11
GI_RESULT_AIR_VENTS             10
GI_REQ_ROOF_ACCESS              11
GI_RESULT_ROOF_ACCESS            7
SI_REQ_SEDIMENT                 11
SI_RESULT_SEDIMENT               9
SI_REQ_BIOLOGICAL_GROWTH        11
SI_RESULT_BIOLOGICAL_GROWTH     10
SI_REQ_DEBRIS_INSECTS           11
SI_RESULT_DEBRIS_INSECTS        10
SI_REQ_RODENT_BIRD              11
SI_RESULT_RODENT_BIRD            7
SAMPLE_COLLECTED                11
LAB_NAME                        11
NYS_CERTIFIED                   11
ANALYTES                         6
COLIFORM                         6
ECOLI                            6
MEET_STANDARDS                  11
DELETED                         11
LATITUDE                        11
LONGITUDE                       11
COMMUNITY_BOARD                 11
COUNCIL_DISTRICT                11
CENSUS_TRACT                    11
BBL                             11
NTA                             11
BATCH_DATE                      11
dtype: int64

In [32]:
df.count()

BIN                             55616
BOROUGH                         55707
ZIP                             55629
HOUSE_NUM                       55707
STREET_NAME                     55707
BLOCK                           55707
LOT                             55707
CONFIRMATION_NUM                55707
REPORTING_YEAR                  55707
TANK_NUM                        55707
INSPECTION_BY_FIRM              55685
INSPECTION_PERFORMED            55707
INSPECTION_DATE                 55685
GI_REQ_INTERNAL_STRUCTURE       55707
GI_RESULT_INTERNAL_STRUCTURE    55610
GI_REQ_EXTERNAL_STRUCTURE       55707
GI_RESULT_EXTERNAL_STRUCTURE    55649
GI_REQ_OVERFLOW_PIPES           55707
GI_RESULT_OVERFLOW_PIPES        55648
GI_REQ_ACCESS_LADDERS           55707
GI_RESULT_ACCESS_LADDERS        55598
GI_REQ_AIR_VENTS                55707
GI_RESULT_AIR_VENTS             55653
GI_REQ_ROOF_ACCESS              55707
GI_RESULT_ROOF_ACCESS           55578
SI_REQ_SEDIMENT                 55707
SI_RESULT_SEDIMENT              55605
SI_REQ_BIOLOGICAL_GROWTH        55707
SI_RESULT_BIOLOGICAL_GROWTH     55604
SI_REQ_DEBRIS_INSECTS           55707
SI_RESULT_DEBRIS_INSECTS        55603
SI_REQ_RODENT_BIRD              55707
SI_RESULT_RODENT_BIRD           55645
SAMPLE_COLLECTED                55701
LAB_NAME                        55590
NYS_CERTIFIED                   55593
ANALYTES                        55597
COLIFORM                        55571
ECOLI                           55571
MEET_STANDARDS                  11127
DELETED                         55707
LATITUDE                        55602
LONGITUDE                       55602
COMMUNITY_BOARD                 55602
COUNCIL_DISTRICT                55602
CENSUS_TRACT                    55602
BBL                             55560
NTA                             55602
BATCH_DATE                      55707
dtype: int64

In [70]:
df["INSPECTION_DATE"] = pd.to_datetime(df["INSPECTION_DATE"], format="%m/%d/%Y")

In [72]:
start_date = pd.Timestamp("2020-01-01")
end_date = pd.Timestamp("2025-04-08")

In [74]:
df20tonow = df[(df["INSPECTION_DATE"] >= start_date) & (df["INSPECTION_DATE"] <= end_date)]

In [78]:
df20tonow.to_csv("Tank Inspection 2020-Present.csv", index=False)

In [82]:
dirtytanks = df20tonow.query("(SI_RESULT_RODENT_BIRD=='A') or (SI_RESULT_DEBRIS_INSECTS=='A') or (COLIFORM=='P') or (ECOLI=='P') or (GI_RESULT_INTERNAL_STRUCTURE =='A') or (SI_RESULT_BIOLOGICAL_GROWTH == 'A') or (GI_RESULT_EXTERNAL_STRUCTURE=='A')" )

In [84]:
dirtytanks.to_csv("Dirty Tanks 2020-Present.csv", index=False)